### ISSUE TITLE
RDS force-scaling-capacity

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/knowledge-base#35]
Should this be applied to all 3 Senzing databases or only the core-cluster as documented?

**Comment by docktermj** [comment]
@christianswanepoel To what are you referring?   If https://github.com/Senzing/knowledge-base/blob/master/HOWTO/set-aws-rds-force-scaling-capacity.md, then "yes",  all 3 databases.

**Comment by christianswanepoel** [comment]
correct the "RDS force-scaling-capacity" ;)
