### ISSUE TITLE
SENZING_API_SERVER_* entries are missing

### ISSUE THREAD

**Issue by antaenc** [Senzing/knowledge-base#49]

**Comment by docktermj** [comment]
@antaenc To be clear,  where are they missing? 

Is it in https://github.com/Senzing/knowledge-base/blob/main/lists/environment-variables.md?

**Comment by antaenc** [comment]
Yes

**Comment by barrycaceres** [comment]
Added `SENZING_API_SERVER` environment variables and made some corrections.
